meta_title: "ShareTheCars - La gestion futuriste de véhicules d'entreprise"
meta_description: "Facilitez  la mobilité au sein de votre entreprise.
  Planifiez et gérez les réservations de véhicules sans effort avec ShareTheCars.
  Simplifiez la gestion de votre flotte et donnez à votre équipe les moyens d'être plus efficace."
meta_image: "Nouveau_projet.png" # should exist in `app/assets/images/`
twitter_account: "@ShareTheCars" # required for Twitter Cards
